In [1]:
import os
from pathlib import Path
import concurrent.futures
import pickle
import mg5qs_import as qs

In [2]:
MG5_PATH = Path(os.getenv('MG5QS_MG5_PATH'))      # where is madgraph?
INPUT_PATH = Path(os.getenv('MG5QS_INPUT_PATH'))  # where is model's proc_card?
qs.edit_card_spec(INPUT_PATH / 'proc_card_bg.dat')

#************************************************************
#*                        MadGraph 5                        *
#*                                                          *
#*                *                       *                 *
#*                  *        * *        *                   *
#*                    * * * * 5 * * * *                     *
#*                  *        * *        *                   *
#*                *                       *                 *
#*                                                          *
#*                                                          *
#*    The MadGraph Development Team - Please visit us at    *
#*    https://server06.fynu.ucl.ac.be/projects/madgraph     *
#*                                                          *
#************************************************************
#*                                                          *
#*               Command File for MadGraph 5                *
#*                                                          *
#*     run as ./bin/mg5  filename                           *
#*                                                          *
#************************************************************

Text(value='set group_subprocesses Auto', layout=Layout(width='550px'))

Text(value='set ignore_six_quark_processes False', layout=Layout(width='550px'))

Text(value='set low_mem_multicore_nlo_generation False', layout=Layout(width='550px'))

Text(value='set complex_mass_scheme False', layout=Layout(width='550px'))

Text(value='set gauge unitary', layout=Layout(width='550px'))

Text(value='set loop_optimized_output True', layout=Layout(width='550px'))

Text(value='set loop_color_flows False', layout=Layout(width='550px'))

Text(value='set max_npoint_for_channel 0', layout=Layout(width='550px'))

Text(value='set default_unset_couplings 99', layout=Layout(width='550px'))

Text(value='set max_t_for_channel 99', layout=Layout(width='550px'))

Text(value='set zerowidth_tchannel True', layout=Layout(width='550px'))

Text(value='import model sm', layout=Layout(width='550px'))

Text(value='define p = g u c d s u~ c~ d~ s~', layout=Layout(width='550px'))

Text(value='define j = g u c d s u~ c~ d~ s~', layout=Layout(width='550px'))

Text(value='define l+ = e+ mu+', layout=Layout(width='550px'))

Text(value='define l- = e- mu-', layout=Layout(width='550px'))

Text(value='define vl = ve vm vt', layout=Layout(width='550px'))

Text(value='define vl~ = ve~ vm~ vt~', layout=Layout(width='550px'))

Text(value='import model /home/leo/MadStats/mg5qs/model/SMEFTsim_general_MwScheme_UFO_bg', layout=Layout(width…

Text(value='mit_bg', layout=Layout(width='550px'))

Text(value='define p = u u~ c c~ d d~ s s~ b b~ g', layout=Layout(width='550px'))

Text(value='generate p p > ta- vt~ SMHLOOP=0 NP<=1', layout=Layout(width='550px'))

Text(value='output cledq__3332_0.02', layout=Layout(width='550px'))

Button(description='Save', style=ButtonStyle())

Output()

In [3]:
output_name, FRAMEWORK_PATH = qs.run_MG5(qs.MG5_PATH, qs.INPUT_PATH, proc_card_name='proc_card_bg.dat')

In [4]:
qs.edit_card(FRAMEWORK_PATH)

#*********************************************************************
#                       MadGraph5_aMC@NLO                            *
#                                                                    *
#                     run_card.dat MadEvent                          *
#                                                                    *
#  This file is used to set the parameters of the run.               *
#                                                                    *
#  Some notation/conventions:                                        *
#                                                                    *
#   Lines starting with a '# ' are info or comments                  *
#                                                                    *
#   mind the format:   value    = variable     ! comment             *
#                                                                    *
#   To display more options, you can type the command:               *
#      update to_full                                                *
#*********************************************************************
#
#*********************************************************************
# Tag name for the run (one word)                                    *
#*********************************************************************

Text(value='tag_1     = run_tag ! name of the run', layout=Layout(width='550px'))

#*********************************************************************
# Number of events and rnd seed                                      *
# Warning: Do not generate more than 1M events in a single run       *
#*********************************************************************

Text(value='10000 = nevents ! Number of unweighted events requested', layout=Layout(width='550px'))

Text(value='0   = iseed   ! rnd seed (0=assigned automatically=default))', layout=Layout(width='550px'))

#*********************************************************************
# Collider type and energy                                           *
# lpp: 0=No PDF, 1=proton, -1=antiproton,                            *
#                2=elastic photon of proton/ion beam                 *
#             +/-3=PDF of electron/positron beam                     *
#             +/-4=PDF of muon/antimuon beam                         *
#*********************************************************************

Text(value='1        = lpp1    ! beam 1 type', layout=Layout(width='550px'))

Text(value='1        = lpp2    ! beam 2 type', layout=Layout(width='550px'))

Text(value='6500.0     = ebeam1  ! beam 1 total energy in GeV', layout=Layout(width='550px'))

Text(value='6500.0     = ebeam2  ! beam 2 total energy in GeV', layout=Layout(width='550px'))

# To see polarised beam options: type "update beam_pol"

#*********************************************************************
# PDF CHOICE: this automatically fixes alpha_s and its evol.         *
# pdlabel: lhapdf=LHAPDF (installation needed) [1412.7420]           *
#          iww=Improved Weizsaecker-Williams Approx.[hep-ph/9310350] *
#          eva=Effective W/Z/A Approx.       [2111.02442]            *
#          edff=EDFF in gamma-UPC            [eq.(11) in 2207.03012] *
#          chff=ChFF in gamma-UPC            [eq.(13) in 2207.03012] *
#          none=No PDF, same as lhapdf with lppx=0                   *
#*********************************************************************

Text(value='nn23lo1    = pdlabel1     ! PDF type for beam #1', layout=Layout(width='550px'))

Text(value='nn23lo1    = pdlabel2     ! PDF type for beam #2', layout=Layout(width='550px'))

Text(value='230000    = lhaid     ! if pdlabel=lhapdf, this is the lhapdf number', layout=Layout(width='550px'…

# To see heavy ion options: type "update ion_pdf"
#*********************************************************************
# Renormalization and factorization scales                           *
#*********************************************************************

Text(value='False = fixed_ren_scale  ! if .true. use fixed ren scale', layout=Layout(width='550px'))

Text(value='False = fixed_fac_scale1  ! if .true. use fixed fac scale for beam 1', layout=Layout(width='550px'…

Text(value='False = fixed_fac_scale2  ! if .true. use fixed fac scale for beam 2', layout=Layout(width='550px'…

Text(value='91.188  = scale            ! fixed ren scale', layout=Layout(width='550px'))

Text(value='91.188  = dsqrt_q2fact1    ! fixed fact scale for pdf1', layout=Layout(width='550px'))

Text(value='91.188  = dsqrt_q2fact2    ! fixed fact scale for pdf2', layout=Layout(width='550px'))

Text(value='-1 = dynamical_scale_choice ! Choose one of the preselected dynamical choices', layout=Layout(widt…

Text(value='1.0  = scalefact        ! scale factor for event-by-event scales', layout=Layout(width='550px'))

#*********************************************************************
# Type and output format
#*********************************************************************

Text(value='False     = gridpack  !True = setting up the grid pack', layout=Layout(width='550px'))

Text(value='-1.0 = time_of_flight ! threshold (in mm) below which the invariant livetime is not written (-1 me…

Text(value='average =  event_norm       ! average/sum. Normalization of the weight in the LHEF', layout=Layout…

# To see MLM/CKKW  merging options: type "update MLM" or "update CKKW"

#*********************************************************************
#
#*********************************************************************
# Phase-Space Optimization strategy (basic options)
#*********************************************************************

Text(value='0  = nhel          ! using helicities importance sampling or not.', layout=Layout(width='550px'))

Text(value='! 0: sum over helicity, 1: importance sampling', layout=Layout(width='550px'))

Text(value='1  = sde_strategy  ! default integration strategy (hep-ph/2021.00773)', layout=Layout(width='550px…

Text(value='! 1 is old strategy (using amp square)', layout=Layout(width='550px'))

Text(value='! 2 is new strategy (using only the denominator)', layout=Layout(width='550px'))

# To see advanced option for Phase-Space optimization: type "update psoptim"
#*********************************************************************
# Customization (custom cuts/scale/bias/...)                         *
# list of files containing fortran function that overwrite default   *
#*********************************************************************

Text(value='= custom_fcts ! List of files containing user hook function', layout=Layout(width='550px'))

#*******************************
# Parton level cuts definition *
#*******************************

Text(value='0.0  = dsqrt_shat ! minimal shat for full process', layout=Layout(width='550px'))

#
#
#*********************************************************************
# BW cutoff (M+/-bwcutoff*Gamma) ! Define on/off-shell for "$" and decay
#*********************************************************************

Text(value='15.0  = bwcutoff      ! (M+/-bwcutoff*Gamma)', layout=Layout(width='550px'))

#*********************************************************************
# Standard Cuts                                                      *
#*********************************************************************
# Minimum and maximum pt's (for max, -1 means no cut)                *
#*********************************************************************

Text(value='10.0  = ptl       ! minimum pt for the charged leptons', layout=Layout(width='550px'))

Text(value="0.0  = misset    ! minimum missing Et (sum of neutrino's momenta)", layout=Layout(width='550px'))

Text(value='-1.0  = ptlmax    ! maximum pt for the charged leptons', layout=Layout(width='550px'))

Text(value="-1.0  = missetmax ! maximum missing Et (sum of neutrino's momenta)", layout=Layout(width='550px'))

Text(value='{} = pt_min_pdg ! pt cut for other particles (use pdg code). Applied on particle and anti-particle…

Text(value='{}\t= pt_max_pdg ! pt cut for other particles (syntax e.g. {6: 100, 25: 50})', layout=Layout(width…

#
# For display option for energy cut in the partonic center of mass frame type 'update ecut'
#
#*********************************************************************
# Maximum and minimum absolute rapidity (for max, -1 means no cut)   *
#*********************************************************************

Text(value='2.5  = etal    ! max rap for the charged leptons', layout=Layout(width='550px'))

Text(value='0.0  = etalmin ! min rap for the charged leptons', layout=Layout(width='550px'))

Text(value='{} = eta_min_pdg ! rap cut for other particles (use pdg code). Applied on particle and anti-partic…

Text(value='{} = eta_max_pdg ! rap cut for other particles (syntax e.g. {6: 2.5, 23: 5})', layout=Layout(width…

#*********************************************************************
# Minimum and maximum DeltaR distance                                *
#*********************************************************************
#*********************************************************************
# Minimum and maximum invariant mass for pairs                       *
#*********************************************************************

Text(value='{} = mxx_min_pdg ! min invariant mass of a pair of particles X/X~ (e.g. {6:250})', layout=Layout(w…

Text(value="{'default': False} = mxx_only_part_antipart ! if True the invariant mass is applied only", layout=…

Text(value='! to pairs of particle/antiparticle and not to pairs of the same pdg codes.', layout=Layout(width=…

#*********************************************************************
# Minimum and maximum invariant mass for all letpons                 *
#*********************************************************************

Text(value='0.0   = mmnl    ! min invariant mass for all letpons (l+- and vl)', layout=Layout(width='550px'))

Text(value='-1.0  = mmnlmax ! max invariant mass for all letpons (l+- and vl)', layout=Layout(width='550px'))

#*********************************************************************
# Minimum and maximum pt for 4-momenta sum of leptons / neutrino     *
#  for pair of lepton includes only same flavor, opposite charge
#*********************************************************************
#*********************************************************************
# Inclusive cuts                                                     *
#*********************************************************************
#*********************************************************************
# maximal pdg code for quark to be considered as a light jet         *
# (otherwise b cuts are applied)                                     *
#*********************************************************************

Text(value='5 = maxjetflavor    ! Maximum jet pdg code', layout=Layout(width='550px'))

#*********************************************************************
#
#*********************************************************************
# Store info for systematics studies                                 *
# WARNING: Do not use for interference type of computation           *
#*********************************************************************

Text(value='True  = use_syst      ! Enable systematics studies', layout=Layout(width='550px'))

#

Text(value='systematics = systematics_program ! none, systematics [python], SysCalc [depreceted, C++]', layout…

Text(value="['--mur=0.5,1,2', '--muf=0.5,1,2', '--pdf=errorset'] = systematics_arguments ! see: https://cp3.ir…

Button(description='Save', style=ButtonStyle())

Output()

In [5]:
card = qs.ParamCard(FRAMEWORK_PATH / 'Cards' / 'param_card.dat')

In [6]:
card = qs.ParamCard(FRAMEWORK_PATH / 'Cards' / 'param_card.dat')
df = card.dfs()['SMEFT']
df[df['comment'].str.startswith('cledqRe3332')]

     key  value      comment
970  971    0.0  cledqRe3332

In [7]:
card.set_value('SMEFT', 971, 2.09)
df = card.dfs()['SMEFT']
df[df['comment'].str.startswith('cledqRe3332')]

     key  value      comment
970  971   2.09  cledqRe3332

In [8]:
RUNS = 100
for n in range(RUNS):
    qs.generate_LHE(card, FRAMEWORK_PATH)

In [9]:
LHEs = qs.get_LHEs(FRAMEWORK_PATH)

In [10]:
output_dir = Path('cledq3332_2.09')  # output path relative to Jupyter
cpu_cores = 5                        # set an appropriate value based on CPU hardware

TAU = 15 # Particle ID for Tau
LHEs = qs.get_LHEs(FRAMEWORK_PATH)

# clear or create output path
if os.path.isdir(output_dir):
    for fname in os.listdir(output_dir):
        if 'pkl' in fname:
            os.remove(output_dir / fname)
else:
    os.mkdir(output_dir)

# function to process a single LHE file, storing result in a pickle file
def process_LHE(n, LHE, PID):
    pTs = qs.generate_pT(PID, LHE)
    params = qs.get_run_params(LHE)
    fname = FRAMEWORK_PATH.name + '3332_10.' + str(n) + '.pkl'   #ADDED "_10" FOR SAFTEY, REMEMBER WHEN DOING READ
    with open(output_dir / fname, 'wb') as f:
        pickle.dump((params, pTs), f)
        f.close()

# run multiple processes in parallel
with concurrent.futures.ProcessPoolExecutor(max_workers=cpu_cores) as executor:
    futures = {executor.submit(process_LHE, i, LHE, TAU): i for i, LHE in enumerate(LHEs)}

 *------------------------------------------------------------------------------------*
 |                                                                                    |
 |  *------------------------------------------------------------------------------*  |
 |  |                                                                              |  |
 |  |                                                                              |  |
 |  |   PPP   Y   Y  TTTTT  H   H  III    A      Welcome to the Lund Monte Carlo!  |  |
 |  |   P  P   Y Y     T    H   H   I    A A     This is PYTHIA version 8.311      |  |
 |  |   PPP     Y      T    HHHHH   I   AAAAA    Last date of change:  8 Mar 2024  |  |
 |  |   P       Y      T    H   H   I   A   A                                      |  |
 |  |   P       Y      T    H   H  III  A   A    Now is 09 Feb 2025 at 20:31:35    |  |
 |  |                                                                              |  |
 |  |   Program documentation and an archive of historic versions is found on:     |  |
 |  |                                                                              |  |
 |  |                               https://pythia.org/                            |  |
 |  |                                                                              |  |
 |  |   PYTHIA is authored by a collaboration consisting of:                       |  |
 |  |                                                                              |  |
 |  |   Javira Altmann, Christian Bierlich, Naomi Cooke, Nishita Desai,            |  |
 |  |   Leif Gellersen, Ilkka Helenius, Philip Ilten, Leif Lonnblad,               |  |
 |  |   Stephen Mrenna, Christian Preuss, Torbjorn Sjostrand, Peter Skands,        |  |
 |  |   Marius Utheim, and Rob Verheyen.                                           |  |
 |  |                                                                              |  |
 |  |   The complete list of authors, including contact information and            |  |
 |  |   affiliations, can be found on https://pythia.org/.                         |  |
 |  |   Problems or bugs should be reported on email at authors@pythia.org.        |  |
 |  |                                                                              |  |
 |  |   The main program reference is C. Bierlich et al,                           |  |
 |  |   'A comprehensive guide to the physics and usage of Pythia 8.3',            |  |
 |  |   SciPost Phys. Codebases 8-r8.3 (2022) [arXiv:2203.11601 [hep-ph]]          |  |
 |  |                                                                              |  |
 |  |   PYTHIA is released under the GNU General Public Licence version 2 or later.|  |
 |  |   Please respect the MCnet Guidelines for Event Generator Authors and Users. |  |
 |  |                                                                              |  |
 |  |   Disclaimer: this program comes without any guarantees.                     |  |
 |  |   Beware of errors and use common sense when interpreting results.           |  |
 |  |                                                                              |  |
 |  |   Copyright (C) 2024 Torbjorn Sjostrand                                      |  |
 |  |                                                                              |  |
 |  |                                                                              |  |
 |  *------------------------------------------------------------------------------*  |
 |                                                                                    |
 *------------------------------------------------------------------------------------*

 *-----------------------  SusyLesHouches SUSY/BSM Interface  ------------------------*
 | Last Change 12 Apr 2017 - P. Skands
 | Parsing: /home/leo/MadStats/mg5qs/output/cledq__3332_2.09/Events/run_72/unweighted_events.lhe
 | (SLHA::readFile) line 296 - storing non-SLHA(2) block: ckmblock
 | (SLHA::readFile) line 323 - storing non-SLHA(2) block: smeft
 | (SLHA::readFile) line 1674 - storing non-SLHA(2) block: smeftcpv
 | (SLHA::readFile) line 2824 - storing non-SLHA(2) block: smeftcutoff
 | (SLHA::readFile) line 2830 - storing non-SLHA(2) block: switches
 | (SLHA::readFile) line 2832 - storing non-SLHA(2) block: yukawa
 | (SLHA::readFile) line 2862 - storing QNUMBERS for id = 9000005 z1
 | (SLHA::readFile) line 2867 - storing QNUMBERS for id = 9000006 w1+
 | (SLHA::readFile) line 2872 - storing QNUMBERS for id = 9000007 t1
 | (SLHA::readFile) line 2877 - storing QNUMBERS for id = 9000008 h1

 *------------------------------------------------------------------------------------*
 |                                                                                    |
 |  *------------------------------------------------------------------------------*  |
 |  |                                                                              |  |
 |  |                                                                              |  |
 |  |   PPP   Y   Y  TTTTT  H   H  III    A      Welcome to the Lund Monte Carlo!  |  |
 |  |   P  P   Y Y     T    H   H   I    A A     This is PYTHIA version 8.311      |  |
 |  |   PPP     Y      T    HHHHH   I   AAAAA    Last date of change:  8 Mar 2024  |  |
 |  |   P       Y      T    H   H   I   A   A                                      |  |
 |  |   P       Y      T    H   H  III  A   A    Now is 09 Feb 2025 at 20:31:35    |  |
 |  |                                                                              |  |
 |  |   Program documentation and an archive of historic versions is found on:     |  |
 |  |                                                                              |  |
 |  |                               https://pythia.org/                            |  |
 |  |                                                                              |  |
 |  |   PYTHIA is authored by a collaboration consisting of:                       |  |
 |  |                                                                              |  |
 |  |   Javira Altmann, Christian Bierlich, Naomi Cooke, Nishita Desai,            |  |
 |  |   Leif Gellersen, Ilkka Helenius, Philip Ilten, Leif Lonnblad,               |  |
 |  |   Stephen Mrenna, Christian Preuss, Torbjorn Sjostrand, Peter Skands,        |  |
 |  |   Marius Utheim, and Rob Verheyen.                                           |  |
 |  |                                                                              |  |
 |  |   The complete list of authors, including contact information and            |  |
 |  |   affiliations, can be found on https://pythia.org/.                         |  |
 |  |   Problems or bugs should be reported on email at authors@pythia.org.        |  |
 |  |                                                                              |  |
 |  |   The main program reference is C. Bierlich et al,                           |  |
 |  |   'A comprehensive guide to the physics and usage of Pythia 8.3',            |  |
 |  |   SciPost Phys. Codebases 8-r8.3 (2022) [arXiv:2203.11601 [hep-ph]]          |  |
 |  |                                                                              |  |
 |  |   PYTHIA is released under the GNU General Public Licence version 2 or later.|  |
 |  |   Please respect the MCnet Guidelines for Event Generator Authors and Users. |  |
 |  |                                                                              |  |
 |  |   Disclaimer: this program comes without any guarantees.                     |  |
 |  |   Beware of errors and use common sense when interpreting results.           |  |
 |  |                                                                              |  |
 |  |   Copyright (C) 2024 Torbjorn Sjostrand                                      |  |
 |  |                                                                              |  |
 |  |                                                                              |  |
 |  *------------------------------------------------------------------------------*  |
 |                                                                                    |
 *------------------------------------------------------------------------------------*


 *------------------------------------------------------------------------------------*
 |                                                                                    |
 |  *------------------------------------------------------------------------------*  |
 |  |                                                                              |  |
 |  |                                                                              |  |
 |  |   PPP   Y   Y  TTTTT  H   H  III    A      Welcome to the Lund Monte Carlo!  |  |
 |  |   P  P   Y Y     T    H   H   I    A A     This is PYTHIA version 8.311      |  |
 |  |   PPP     Y      T    HHHHH   I   AAAAA    Last date of change:  8 Mar 2024  |  |
 |  |   P       Y      T    H   H   I   A   A                                      |  |
 |  |   P       Y      T    H   H  III  A   A    Now is 09 Feb 2025 at 20:31:35    |  |
 |  |                                                                              |  |
 |  |   Program documentation and an archive of historic versions is found on:     |  |
 |  |                                                                              |  |
 |  |                               https://pythia.org/                            |  |
 |  |                                                                              |  |
 |  |   PYTHIA is authored by a collaboration consisting of:                       |  |
 |  |                                                                              |  |
 |  |   Javira Altmann, Christian Bierlich, Naomi Cooke, Nishita Desai,            |  |
 |  |   Leif Gellersen, Ilkka Helenius, Philip Ilten, Leif Lonnblad,               |  |
 |  |   Stephen Mrenna, Christian Preuss, Torbjorn Sjostrand, Peter Skands,        |  |
 |  |   Marius Utheim, and Rob Verheyen.                                           |  |
 |  |                                                                              |  |
 |  |   The complete list of authors, including contact information and            |  |
 |  |   affiliations, can be found on https://pythia.org/.                         |  |
 |  |   Problems or bugs should be reported on email at authors@pythia.org.        |  |
 |  |                                                                              |  |
 |  |   The main program reference is C. Bierlich et al,                           |  |
 |  |   'A comprehensive guide to the physics and usage of Pythia 8.3',            |  |
 |  |   SciPost Phys. Codebases 8-r8.3 (2022) [arXiv:2203.11601 [hep-ph]]          |  |
 |  |                                                                              |  |
 |  |   PYTHIA is released under the GNU General Public Licence version 2 or later.|  |
 |  |   Please respect the MCnet Guidelines for Event Generator Authors and Users. |  |
 |  |                                                                              |  |
 |  |   Disclaimer: this program comes without any guarantees.                     |  |
 |  |   Beware of errors and use common sense when interpreting results.           |  |
 |  |                                                                              |  |
 |  |   Copyright (C) 2024 Torbjorn Sjostrand                                      |  |
 |  |                                                                              |  |
 |  |                                                                              |  |
 |  *------------------------------------------------------------------------------*  |
 |                                                                                    |
 *------------------------------------------------------------------------------------*


 *------------------------------------------------------------------------------------*
 |                                                                                    |
 |  *------------------------------------------------------------------------------*  |
 |  |                                                                              |  |
 |  |                                                                              |  |
 |  |   PPP   Y   Y  TTTTT  H   H  III    A      Welcome to the Lund Monte Carlo!  |  |
 |  |   P  P   Y Y     T    H   H   I    A A     This is PYTHIA version 8.311      |  |
 |  |   PPP     Y      T    HHHHH   I   AAAAA    Last date of change:  8 Mar 2024  |  |
 |  |   P       Y      T    H   H   I   A   A                                      |  |
 |  |   P       Y      T    H   H  III  A   A    Now is 09 Feb 2025 at 20:31:35    |  |
 |  |                                                                              |  |
 |  |   Program documentation and an archive of historic versions is found on:     |  |
 |  |                                                                              |  |
 |  |                               https://pythia.org/                            |  |
 |  |                                                                              |  |
 |  |   PYTHIA is authored by a collaboration consisting of:                       |  |
 |  |                                                                              |  |
 |  |   Javira Altmann, Christian Bierlich, Naomi Cooke, Nishita Desai,            |  |
 |  |   Leif Gellersen, Ilkka Helenius, Philip Ilten, Leif Lonnblad,               |  |
 |  |   Stephen Mrenna, Christian Preuss, Torbjorn Sjostrand, Peter Skands,        |  |
 |  |   Marius Utheim, and Rob Verheyen.                                           |  |
 |  |                                                                              |  |
 |  |   The complete list of authors, including contact information and            |  |
 |  |   affiliations, can be found on https://pythia.org/.                         |  |
 |  |   Problems or bugs should be reported on email at authors@pythia.org.        |  |
 |  |                                                                              |  |
 |  |   The main program reference is C. Bierlich et al,                           |  |
 |  |   'A comprehensive guide to the physics and usage of Pythia 8.3',            |  |
 |  |   SciPost Phys. Codebases 8-r8.3 (2022) [arXiv:2203.11601 [hep-ph]]          |  |
 |  |                                                                              |  |
 |  |   PYTHIA is released under the GNU General Public Licence version 2 or later.|  |
 |  |   Please respect the MCnet Guidelines for Event Generator Authors and Users. |  |
 |  |                                                                              |  |
 |  |   Disclaimer: this program comes without any guarantees.                     |  |
 |  |   Beware of errors and use common sense when interpreting results.           |  |
 |  |                                                                              |  |
 |  |   Copyright (C) 2024 Torbjorn Sjostrand                                      |  |
 |  |                                                                              |  |
 |  |                                                                              |  |
 |  *------------------------------------------------------------------------------*  |
 |                                                                                    |
 *------------------------------------------------------------------------------------*


 *------------------------------------------------------------------------------------*
 |                                                                                    |
 |  *------------------------------------------------------------------------------*  |
 |  |                                                                              |  |
 |  |                                                                              |  |
 |  |   PPP   Y   Y  TTTTT  H   H  III    A      Welcome to the Lund Monte Carlo!  |  |
 |  |   P  P   Y Y     T    H   H   I    A A     This is PYTHIA version 8.311      |  |
 |  |   PPP     Y      T    HHHHH   I   AAAAA    Last date of change:  8 Mar 2024  |  |
 |  |   P       Y      T    H   H   I   A   A                                      |  |
 |  |   P       Y      T    H   H  III  A   A    Now is 09 Feb 2025 at 20:31:35    |  |
 |  |                                                                              |  |
 |  |   Program documentation and an archive of historic versions is found on:     |  |
 |  |                                                                              |  |
 |  |                               https://pythia.org/                            |  |
 |  |                                                                              |  |
 |  |   PYTHIA is authored by a collaboration consisting of:                       |  |
 |  |                                                                              |  |
 |  |   Javira Altmann, Christian Bierlich, Naomi Cooke, Nishita Desai,            |  |
 |  |   Leif Gellersen, Ilkka Helenius, Philip Ilten, Leif Lonnblad,               |  |
 |  |   Stephen Mrenna, Christian Preuss, Torbjorn Sjostrand, Peter Skands,        |  |
 |  |   Marius Utheim, and Rob Verheyen.                                           |  |
 |  |                                                                              |  |
 |  |   The complete list of authors, including contact information and            |  |
 |  |   affiliations, can be found on https://pythia.org/.                         |  |
 |  |   Problems or bugs should be reported on email at authors@pythia.org.        |  |
 |  |                                                                              |  |
 |  |   The main program reference is C. Bierlich et al,                           |  |
 |  |   'A comprehensive guide to the physics and usage of Pythia 8.3',            |  |
 |  |   SciPost Phys. Codebases 8-r8.3 (2022) [arXiv:2203.11601 [hep-ph]]          |  |
 |  |                                                                              |  |
 |  |   PYTHIA is released under the GNU General Public Licence version 2 or later.|  |
 |  |   Please respect the MCnet Guidelines for Event Generator Authors and Users. |  |
 |  |                                                                              |  |
 |  |   Disclaimer: this program comes without any guarantees.                     |  |
 |  |   Beware of errors and use common sense when interpreting results.           |  |
 |  |                                                                              |  |
 |  |   Copyright (C) 2024 Torbjorn Sjostrand                                      |  |
 |  |                                                                              |  |
 |  |                                                                              |  |
 |  *------------------------------------------------------------------------------*  |
 |                                                                                    |
 *------------------------------------------------------------------------------------*

 *-----------------------  SusyLesHouches SUSY/BSM Interface  ------------------------*
 | Last Change 12 Apr 2017 - P. Skands
 | Parsing: /home/leo/MadStats/mg5qs/output/cledq__3332_2.09/Events/run_17/unweighted_events.lhe
 | (SLHA::readFile) line 296 - storing non-SLHA(2) block: ckmblock
 | (SLHA::readFile) line 323 - storing non-SLHA(2) block: smeft
 *-----------------------  SusyLesHouches SUSY/BSM Interface  ------------------------*
 | Last Change 12 Apr 2017 - P. Skands
 | Parsing: /home/leo/MadStats/mg5qs/output/cledq__3332_2.09/Events/run_34/unweighted_events.lhe