In [1]:
import mg5qs_import as qs
from pathlib import Path

In [2]:
LHE = Path('/home/leo/MadStats/mg5qs/output/cledq__3332_SM_small/Events/run_01/unweighted_events.lhe')
result, pTs, status = qs.generate_vals(15, LHE)

 *------------------------------------------------------------------------------------*
 |                                                                                    |
 |  *------------------------------------------------------------------------------*  |
 |  |                                                                              |  |
 |  |                                                                              |  |
 |  |   PPP   Y   Y  TTTTT  H   H  III    A      Welcome to the Lund Monte Carlo!  |  |
 |  |   P  P   Y Y     T    H   H   I    A A     This is PYTHIA version 8.311      |  |
 |  |   PPP     Y      T    HHHHH   I   AAAAA    Last date of change:  8 Mar 2024  |  |
 |  |   P       Y      T    H   H   I   A   A                                      |  |
 |  |   P       Y      T    H   H  III  A   A    Now is 28 Jan 2025 at 15:55:28    |  |
 |  |                                                                              |  |
 |  |   Program documentation and an archive of historic versions is found on:     |  |
 |  |                                                                              |  |
 |  |                               https://pythia.org/                            |  |
 |  |                                                                              |  |
 |  |   PYTHIA is authored by a collaboration consisting of:                       |  |
 |  |                                                                              |  |
 |  |   Javira Altmann, Christian Bierlich, Naomi Cooke, Nishita Desai,            |  |
 |  |   Leif Gellersen, Ilkka Helenius, Philip Ilten, Leif Lonnblad,               |  |
 |  |   Stephen Mrenna, Christian Preuss, Torbjorn Sjostrand, Peter Skands,        |  |
 |  |   Marius Utheim, and Rob Verheyen.                                           |  |
 |  |                                                                              |  |
 |  |   The complete list of authors, including contact information and            |  |
 |  |   affiliations, can be found on https://pythia.org/.                         |  |
 |  |   Problems or bugs should be reported on email at authors@pythia.org.        |  |
 |  |                                                                              |  |
 |  |   The main program reference is C. Bierlich et al,                           |  |
 |  |   'A comprehensive guide to the physics and usage of Pythia 8.3',            |  |
 |  |   SciPost Phys. Codebases 8-r8.3 (2022) [arXiv:2203.11601 [hep-ph]]          |  |
 |  |                                                                              |  |
 |  |   PYTHIA is released under the GNU General Public Licence version 2 or later.|  |
 |  |   Please respect the MCnet Guidelines for Event Generator Authors and Users. |  |
 |  |                                                                              |  |
 |  |   Disclaimer: this program comes without any guarantees.                     |  |
 |  |   Beware of errors and use common sense when interpreting results.           |  |
 |  |                                                                              |  |
 |  |   Copyright (C) 2024 Torbjorn Sjostrand                                      |  |
 |  |                                                                              |  |
 |  |                                                                              |  |
 |  *------------------------------------------------------------------------------*  |
 |                                                                                    |
 *------------------------------------------------------------------------------------*

 *-----------------------  SusyLesHouches SUSY/BSM Interface  ------------------------*
 | Last Change 12 Apr 2017 - P. Skands
 | Parsing: /home/leo/MadStats/mg5qs/output/cledq__3332_SM_small/Events/run_01/unweighted_events.lhe
 | (SLHA::readFile) line 296 - storing non-SLHA(2) block: ckmblock
 | (SLHA::readFile) line 323 - storing non-SLHA(2) block: smeft
 | (SLHA::readFile) line 1674 - storing non-SLHA(2) block: smeftcpv
 | (SLHA::readFile) line 2824 - storing non-SLHA(2) block: smeftcutoff
 | (SLHA::readFile) line 2830 - storing non-SLHA(2) block: switches
 | (SLHA::readFile) line 2832 - storing non-SLHA(2) block: yukawa
 | (SLHA::readFile) line 2862 - storing QNUMBERS for id = 9000005 z1
 | (SLHA::readFile) line 2867 - storing QNUMBERS for id = 9000006 w1+
 | (SLHA::readFile) line 2872 - storing QNUMBERS for id = 9000007 t1
 | (SLHA::readFile) line 2877 - storing QNUMBERS for id = 9000008 h1

In [3]:
import pandas as pd

In [5]:
df = pd.DataFrame(status.T, columns = result['fields'].split(','))
df

,EVENT,INDEX,STATUS,ISFINAL,ISCHARGED,MOTHER1,MOTHER2,MOTHER1ID,MOTHER2ID,DAUGHTER1,DAUGHTER2
0,1,271,-23,0,1,203,0,-24,90,273,274
1,1,273,-51,0,1,271,0,15,90,525,527
2,2,64,-23,0,1,48,0,-24,90,129,131
3,3,409,-23,0,1,319,0,-24,90,725,727
4,4,159,-23,0,1,124,0,-24,90,161,162
...,...,...,...,...,...,...,...,...,...,...,...
1371,998,346,-23,0,1,259,0,-24,90,687,689
1372,999,456,-23,0,1,351,0,-24,90,458,459
1373,999,458,-51,0,1,456,0,15,90,842,846
1374,1000,497,-23,0,1,377,0,-24,90,499,500
1375,1000,499,-51,0,1,497,0,15,90,890,892

In [6]:
dup_event = df['EVENT'].value_counts()>1 # events with more than 1 tau
df[df['EVENT'].isin(dup_event[dup_event].index)] # details about such taus

,EVENT,INDEX,STATUS,ISFINAL,ISCHARGED,MOTHER1,MOTHER2,MOTHER1ID,MOTHER2ID,DAUGHTER1,DAUGHTER2
0,1,271,-23,0,1,203,0,-24,90,273,274
1,1,273,-51,0,1,271,0,15,90,525,527
4,4,159,-23,0,1,124,0,-24,90,161,162
5,4,161,-51,0,1,159,0,15,90,329,332
6,5,124,-23,0,1,92,0,-24,90,126,127
...,...,...,...,...,...,...,...,...,...,...,...
1369,996,208,-51,0,1,206,0,15,90,430,432
1372,999,456,-23,0,1,351,0,-24,90,458,459
1373,999,458,-51,0,1,456,0,15,90,842,846
1374,1000,497,-23,0,1,377,0,-24,90,499,500
1375,1000,499,-51,0,1,497,0,15,90,890,892

In [8]:
df['MOTHER1ID'].abs().value_counts() #abs of particle for all imeadite par

MOTHER1ID
24     993
15     369
431      4
2        3
521      3
3        2
1        2
Name: count, dtype: int64