In [1]:
import mg5qs_import as qs
from pathlib import Path

In [2]:
LHE = Path('/home/leo/MadStats/mg5qs/output/cledq__3332_SM_small/Events/run_01/unweighted_events.lhe')
result, four_momenta, status = qs.generate_vals(15, LHE)

 *------------------------------------------------------------------------------------*
 |                                                                                    |
 |  *------------------------------------------------------------------------------*  |
 |  |                                                                              |  |
 |  |                                                                              |  |
 |  |   PPP   Y   Y  TTTTT  H   H  III    A      Welcome to the Lund Monte Carlo!  |  |
 |  |   P  P   Y Y     T    H   H   I    A A     This is PYTHIA version 8.311      |  |
 |  |   PPP     Y      T    HHHHH   I   AAAAA    Last date of change:  8 Mar 2024  |  |
 |  |   P       Y      T    H   H   I   A   A                                      |  |
 |  |   P       Y      T    H   H  III  A   A    Now is 18 Feb 2025 at 17:50:16    |  |
 |  |                                                                              |  |
 |  |   Program documentation and an archive of historic versions is found on:     |  |
 |  |                                                                              |  |
 |  |                               https://pythia.org/                            |  |
 |  |                                                                              |  |
 |  |   PYTHIA is authored by a collaboration consisting of:                       |  |
 |  |                                                                              |  |
 |  |   Javira Altmann, Christian Bierlich, Naomi Cooke, Nishita Desai,            |  |
 |  |   Leif Gellersen, Ilkka Helenius, Philip Ilten, Leif Lonnblad,               |  |
 |  |   Stephen Mrenna, Christian Preuss, Torbjorn Sjostrand, Peter Skands,        |  |
 |  |   Marius Utheim, and Rob Verheyen.                                           |  |
 |  |                                                                              |  |
 |  |   The complete list of authors, including contact information and            |  |
 |  |   affiliations, can be found on https://pythia.org/.                         |  |
 |  |   Problems or bugs should be reported on email at authors@pythia.org.        |  |
 |  |                                                                              |  |
 |  |   The main program reference is C. Bierlich et al,                           |  |
 |  |   'A comprehensive guide to the physics and usage of Pythia 8.3',            |  |
 |  |   SciPost Phys. Codebases 8-r8.3 (2022) [arXiv:2203.11601 [hep-ph]]          |  |
 |  |                                                                              |  |
 |  |   PYTHIA is released under the GNU General Public Licence version 2 or later.|  |
 |  |   Please respect the MCnet Guidelines for Event Generator Authors and Users. |  |
 |  |                                                                              |  |
 |  |   Disclaimer: this program comes without any guarantees.                     |  |
 |  |   Beware of errors and use common sense when interpreting results.           |  |
 |  |                                                                              |  |
 |  |   Copyright (C) 2024 Torbjorn Sjostrand                                      |  |
 |  |                                                                              |  |
 |  |                                                                              |  |
 |  *------------------------------------------------------------------------------*  |
 |                                                                                    |
 *------------------------------------------------------------------------------------*

 *-----------------------  SusyLesHouches SUSY/BSM Interface  ------------------------*
 | Last Change 12 Apr 2017 - P. Skands
 | Parsing: /home/leo/MadStats/mg5qs/output/cledq__3332_SM_small/Events/run_01/unweighted_events.lhe
 | (SLHA::readFile) line 296 - storing non-SLHA(2) block: ckmblock
 | (SLHA::readFile) line 323 - storing non-SLHA(2) block: smeft
 | (SLHA::readFile) line 1674 - storing non-SLHA(2) block: smeftcpv
 | (SLHA::readFile) line 2824 - storing non-SLHA(2) block: smeftcutoff
 | (SLHA::readFile) line 2830 - storing non-SLHA(2) block: switches
 | (SLHA::readFile) line 2832 - storing non-SLHA(2) block: yukawa
 | (SLHA::readFile) line 2862 - storing QNUMBERS for id = 9000005 z1
 | (SLHA::readFile) line 2867 - storing QNUMBERS for id = 9000006 w1+
 | (SLHA::readFile) line 2872 - storing QNUMBERS for id = 9000007 t1
 | (SLHA::readFile) line 2877 - storing QNUMBERS for id = 9000008 h1

In [3]:
import pandas as pd

In [4]:
df_stat = pd.DataFrame(status, columns = result['fields'].split(','))
df_mom = pd.DataFrame(four_momenta, columns=['px','py','pz','E'])
df = pd.concat([df_stat, df_mom], axis=1)
df

,EVENT,INDEX,STATUS,ISFINAL,ISCHARGED,MOTHER1,MOTHER2,MOTHER1ID,MOTHER2ID,DAUGHTER1,DAUGHTER2,DAUGHTER1ID,DAUGHTER2ID,DUPLICATED,CHAIN,px,py,pz,E
0,1,225,-23,0,1,177,0,-24,90,392,394,16,-14,0,1,-25.660001,-14.002488,33.514967,44.507483
1,2,786,-23,0,1,610,0,-24,90,1384,1385,16,-211,0,1,9.202997,-12.775829,-5.996804,16.942147
2,3,1113,-23,0,1,830,0,-24,90,1928,1930,16,-14,0,1,-28.512979,-11.648434,-41.200895,51.471812
3,4,809,-23,0,1,613,0,-24,90,1386,1388,16,-12,0,1,4.088566,-34.364095,8.166300,35.601314
4,5,414,-23,0,1,307,0,-24,90,783,785,16,-14,0,1,-10.493154,36.365950,-60.585155,71.458431
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14249,9997,923,-23,0,1,685,0,-24,90,1644,1646,16,-211,0,1,-28.324355,20.206664,-26.823963,43.968865
14250,9998,696,-23,0,1,517,0,-24,90,1277,1279,16,-211,0,1,-6.913908,11.976198,-5.509949,14.991621
14251,9999,575,-23,0,1,449,0,-24,90,1042,1044,16,-14,0,1,-24.797459,19.678103,-167.463085,170.438213
14252,10000,943,-23,0,1,709,0,-24,90,945,946,15,22,1,1,29.328567,-29.556980,-19.698692,46.097463
14253,10000,945,-51,0,1,943,0,15,90,1654,1656,16,-211,0,1,29.328567,-29.556980,-19.698692,46.097463

In [5]:
dup_event = df['EVENT'].value_counts()>1 # events with more than 1 tau
df_dup = df[df['EVENT'].isin(dup_event[dup_event].index)] # details about such taus
df_dup

,EVENT,INDEX,STATUS,ISFINAL,ISCHARGED,MOTHER1,MOTHER2,MOTHER1ID,MOTHER2ID,DAUGHTER1,DAUGHTER2,DAUGHTER1ID,DAUGHTER2ID,DUPLICATED,CHAIN,px,py,pz,E
6,7,978,-23,0,1,742,0,-24,90,980,981,15,22,1,1,28.722137,8.846051,47.058765,55.865006
7,7,980,-51,0,1,978,0,15,90,1660,1661,16,-211,0,1,28.720446,8.845973,47.054696,55.860696
8,8,567,-23,0,1,429,0,-24,90,569,570,15,22,1,1,-8.347577,35.966287,-103.635618,110.030699
9,8,569,-51,0,1,567,0,15,90,572,573,15,22,1,1,-6.743711,34.279172,-97.155456,103.261221
10,8,572,-51,0,1,569,0,15,90,996,998,16,-211,0,1,-6.743711,34.279172,-97.155456,103.261220
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14246,9995,70,-51,0,1,68,0,15,90,158,160,16,-12,0,1,24.383594,3.618655,5.778897,25.381247
14247,9996,694,-23,0,1,512,0,-24,90,696,697,15,22,1,1,-22.489028,23.185555,88.579767,94.301958
14248,9996,696,-51,0,1,694,0,15,90,1213,1214,16,-211,0,1,-22.292096,22.997921,87.788844,93.465933
14252,10000,943,-23,0,1,709,0,-24,90,945,946,15,22,1,1,29.328567,-29.556980,-19.698692,46.097463
14253,10000,945,-51,0,1,943,0,15,90,1654,1656,16,-211,0,1,29.328567,-29.556980,-19.698692,46.097463

In [6]:
df_dup['EVENT'].shape, df_dup['EVENT'].unique().shape

((7903,), (3649,))

In [7]:
df['MOTHER1ID'].abs().value_counts() #abs of particle for all imeadite par

MOTHER1ID
24      9875
15      4155
431       73
1         54
2         43
4         15
3         13
511       11
521        5
531        4
411        3
5122       2
5232       1
Name: count, dtype: int64

In [8]:
df['STATUS'].value_counts()

STATUS
-23    10000
-51     3564
-44      453
-62      125
-91       98
-52       13
-92        1
Name: count, dtype: int64

In [9]:
df['ISFINAL'].sum()

np.int64(0)

Investagae daughters (if daughter1=daughter2>0 => carbon copy of .this):

In [10]:
df_cc = df[df['DAUGHTER1']==df['DAUGHTER2']]
df_cc

,EVENT,INDEX,STATUS,ISFINAL,ISCHARGED,MOTHER1,MOTHER2,MOTHER1ID,MOTHER2ID,DAUGHTER1,DAUGHTER2,DAUGHTER1ID,DAUGHTER2ID,DUPLICATED,CHAIN,px,py,pz,E
38,30,5,-23,0,1,3,4,1,-2,9,9,15,15,1,1,-10.598916,-7.012125,15.253155,19.932972
39,30,9,-44,0,1,5,5,15,15,14,14,15,15,1,1,-8.615897,1.119667,23.857909,25.452797
40,30,14,-44,0,1,9,9,15,15,23,23,15,15,1,1,-8.252050,-2.482299,24.784087,26.299559
41,30,23,-44,0,1,14,14,15,15,34,34,15,15,1,1,-9.412178,-1.606249,24.893041,26.720598
42,30,34,-44,0,1,23,23,15,15,77,77,15,15,1,1,-9.379080,-0.998964,24.974994,26.755805
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13728,9617,628,-51,0,1,625,0,15,90,633,633,15,15,1,1,-3.559942,-46.815169,-0.997084,46.994522
13901,9740,5,-23,0,1,3,4,1,-2,9,9,15,15,1,1,36.818670,36.345703,91.660001,105.267935
13902,9740,9,-44,0,1,5,5,15,15,14,14,15,15,1,1,40.558175,35.795471,100.489454,114.138378
13903,9740,14,-44,0,1,9,9,15,15,267,267,15,15,1,1,41.859721,34.887633,99.669751,113.607219
14030,9830,611,-51,0,1,5,0,15,90,616,616,15,15,1,1,-0.260963,12.650683,-25.236312,28.286694

In [11]:
df['EVENT'].value_counts()

EVENT
8969    11
1443    10
1936    10
5531    10
2282    10
        ..
3664     1
9987     1
9989     1
9990     1
9991     1
Name: count, Length: 10000, dtype: int64

In [12]:
df[df['EVENT']==2425]

,EVENT,INDEX,STATUS,ISFINAL,ISCHARGED,MOTHER1,MOTHER2,MOTHER1ID,MOTHER2ID,DAUGHTER1,DAUGHTER2,DAUGHTER1ID,DAUGHTER2ID,DUPLICATED,CHAIN,px,py,pz,E
3465,2425,5,-23,0,1,3,4,3,-4,48,48,15,15,1,1,-27.794325,-47.045536,0.996289,54.680502
3466,2425,48,-44,0,1,5,5,15,15,68,68,15,15,1,1,-28.128742,-47.670048,1.318896,55.394555
3467,2425,68,-44,0,1,48,48,15,15,100,100,15,15,1,1,-26.136505,-46.224270,4.018126,53.283235
3468,2425,100,-44,0,1,68,68,15,15,121,121,15,15,1,1,-26.419998,-46.056871,3.904504,53.269640
3469,2425,121,-44,0,1,100,100,15,15,516,516,15,15,1,1,-24.933452,-45.220544,5.347522,51.945436
3470,2425,516,-44,0,1,121,121,15,15,534,534,15,15,1,1,-24.980724,-45.003458,5.500075,51.795331
3471,2425,534,-62,0,1,516,516,15,15,1173,1177,16,-211,0,1,-24.833523,-43.766302,6.364777,50.752943

In [13]:
df[df['EVENT']==2873]

,EVENT,INDEX,STATUS,ISFINAL,ISCHARGED,MOTHER1,MOTHER2,MOTHER1ID,MOTHER2ID,DAUGHTER1,DAUGHTER2,DAUGHTER1ID,DAUGHTER2ID,DUPLICATED,CHAIN,px,py,pz,E
4130,2873,5,-23,0,1,3,4,1,-2,9,9,15,15,1,1,-19.535176,-39.460210,82.629090,93.645371
4131,2873,9,-44,0,1,5,5,15,15,14,14,15,15,1,1,-16.987436,-40.555107,74.976547,86.936356
4132,2873,14,-44,0,1,9,9,15,15,276,276,15,15,1,1,-17.164407,-30.631754,79.139092,86.597198
4133,2873,276,-44,0,1,14,14,15,15,288,288,15,15,1,1,-17.427297,-30.085150,79.286609,86.593019
4134,2873,288,-44,0,1,276,276,15,15,704,705,15,22,1,1,-17.399528,-29.994571,78.742483,86.057854
4135,2873,704,-51,0,1,288,0,15,90,709,709,15,15,1,1,-17.398902,-29.993308,78.739224,86.054305
4136,2873,709,-62,0,1,704,704,15,15,1636,1640,16,-321,0,1,-17.801793,-30.038192,79.379791,86.738145

In [14]:
df[df['DUPLICATED']==0].shape

(10099, 19)

In [15]:
df.shape

(14254, 19)

We want to find all events with more than 1 unique tau (i.e. not in the same chain). We will do this by finding the events for which the number of taus exceeds the number of duplicates by more than 1 (every chain will terminate with duplicate=0, so we must have **more** than 1 chain termination).

In [16]:
A = df['EVENT'].value_counts() # numbers of taus per event
B = df[df['DUPLICATED']==True]['EVENT'].value_counts() # number duplicates per event
a,b = A.align(B) # alligns a and b (order and shape) 
a[(a-b.fillna(0))>1] # events for which non-duplicates exceeds 1 (more than 1 chain)

EVENT
120     3
164     2
286     3
287     3
361     2
       ..
9593    4
9647    2
9846    2
9886    2
9944    2
Name: count, Length: 98, dtype: int64

In [18]:
df[df['EVENT']==120]

,EVENT,INDEX,STATUS,ISFINAL,ISCHARGED,MOTHER1,MOTHER2,MOTHER1ID,MOTHER2ID,DAUGHTER1,DAUGHTER2,DAUGHTER1ID,DAUGHTER2ID,DUPLICATED,CHAIN,px,py,pz,E
168,120,1313,-23,0,1,972,0,-24,90,1315,1316,15,22,1,1,-12.452748,-37.788846,138.645814,144.252858
169,120,1315,-51,0,1,1313,0,15,90,2112,2115,16,-211,0,1,-12.452456,-37.787895,138.642591,144.249487
170,120,2545,-91,0,1,2246,0,431,90,2632,2635,-16,-211,0,2,-2.599796,3.911895,-22.708041,23.256700

In [27]:
df[df['CHAIN']>2]

,EVENT,INDEX,STATUS,ISFINAL,ISCHARGED,MOTHER1,MOTHER2,MOTHER1ID,MOTHER2ID,DAUGHTER1,DAUGHTER2,DAUGHTER1ID,DAUGHTER2ID,DUPLICATED,CHAIN,px,py,pz,E
8429,5900,1476,-91,0,1,1456,0,-431,90,1490,1493,16,-211,0,3,-0.718506,1.284411,-29.338999,29.429575

In [28]:
df[df['EVENT']==5900]

,EVENT,INDEX,STATUS,ISFINAL,ISCHARGED,MOTHER1,MOTHER2,MOTHER1ID,MOTHER2ID,DAUGHTER1,DAUGHTER2,DAUGHTER1ID,DAUGHTER2ID,DUPLICATED,CHAIN,px,py,pz,E
8427,5900,552,-23,0,1,420,0,-24,90,1078,1080,16,-12,0,1,23.835077,-2.854302,-45.839708,51.775423
8428,5900,1117,-92,0,1,660,0,-531,90,1371,1373,-16,14,0,2,-0.645285,-0.287427,-9.391153,9.583833
8429,5900,1476,-91,0,1,1456,0,-431,90,1490,1493,16,-211,0,3,-0.718506,1.284411,-29.338999,29.429575