In [1]:
import mg5qs_import as qs
from pathlib import Path

In [2]:
LHE = Path('/home/leo/MadStats/mg5qs/output/cledq__3332_SM_small/Events/run_01/unweighted_events.lhe')
result, pTs, status = qs.generate_vals(15, LHE)

 *------------------------------------------------------------------------------------*
 |                                                                                    |
 |  *------------------------------------------------------------------------------*  |
 |  |                                                                              |  |
 |  |                                                                              |  |
 |  |   PPP   Y   Y  TTTTT  H   H  III    A      Welcome to the Lund Monte Carlo!  |  |
 |  |   P  P   Y Y     T    H   H   I    A A     This is PYTHIA version 8.311      |  |
 |  |   PPP     Y      T    HHHHH   I   AAAAA    Last date of change:  8 Mar 2024  |  |
 |  |   P       Y      T    H   H   I   A   A                                      |  |
 |  |   P       Y      T    H   H  III  A   A    Now is 09 Feb 2025 at 11:07:35    |  |
 |  |                                                                              |  |
 |  |   Program documentation and an archive of historic versions is found on:     |  |
 |  |                                                                              |  |
 |  |                               https://pythia.org/                            |  |
 |  |                                                                              |  |
 |  |   PYTHIA is authored by a collaboration consisting of:                       |  |
 |  |                                                                              |  |
 |  |   Javira Altmann, Christian Bierlich, Naomi Cooke, Nishita Desai,            |  |
 |  |   Leif Gellersen, Ilkka Helenius, Philip Ilten, Leif Lonnblad,               |  |
 |  |   Stephen Mrenna, Christian Preuss, Torbjorn Sjostrand, Peter Skands,        |  |
 |  |   Marius Utheim, and Rob Verheyen.                                           |  |
 |  |                                                                              |  |
 |  |   The complete list of authors, including contact information and            |  |
 |  |   affiliations, can be found on https://pythia.org/.                         |  |
 |  |   Problems or bugs should be reported on email at authors@pythia.org.        |  |
 |  |                                                                              |  |
 |  |   The main program reference is C. Bierlich et al,                           |  |
 |  |   'A comprehensive guide to the physics and usage of Pythia 8.3',            |  |
 |  |   SciPost Phys. Codebases 8-r8.3 (2022) [arXiv:2203.11601 [hep-ph]]          |  |
 |  |                                                                              |  |
 |  |   PYTHIA is released under the GNU General Public Licence version 2 or later.|  |
 |  |   Please respect the MCnet Guidelines for Event Generator Authors and Users. |  |
 |  |                                                                              |  |
 |  |   Disclaimer: this program comes without any guarantees.                     |  |
 |  |   Beware of errors and use common sense when interpreting results.           |  |
 |  |                                                                              |  |
 |  |   Copyright (C) 2024 Torbjorn Sjostrand                                      |  |
 |  |                                                                              |  |
 |  |                                                                              |  |
 |  *------------------------------------------------------------------------------*  |
 |                                                                                    |
 *------------------------------------------------------------------------------------*

 *-----------------------  SusyLesHouches SUSY/BSM Interface  ------------------------*
 | Last Change 12 Apr 2017 - P. Skands
 | Parsing: /home/leo/MadStats/mg5qs/output/cledq__3332_SM_small/Events/run_01/unweighted_events.lhe
 | (SLHA::readFile) line 296 - storing non-SLHA(2) block: ckmblock
 | (SLHA::readFile) line 323 - storing non-SLHA(2) block: smeft
 | (SLHA::readFile) line 1674 - storing non-SLHA(2) block: smeftcpv
 | (SLHA::readFile) line 2824 - storing non-SLHA(2) block: smeftcutoff
 | (SLHA::readFile) line 2830 - storing non-SLHA(2) block: switches
 | (SLHA::readFile) line 2832 - storing non-SLHA(2) block: yukawa
 | (SLHA::readFile) line 2862 - storing QNUMBERS for id = 9000005 z1
 | (SLHA::readFile) line 2867 - storing QNUMBERS for id = 9000006 w1+
 | (SLHA::readFile) line 2872 - storing QNUMBERS for id = 9000007 t1
 | (SLHA::readFile) line 2877 - storing QNUMBERS for id = 9000008 h1

In [3]:
import pandas as pd

In [4]:
df = pd.DataFrame(status.T, columns = result['fields'].split(','))
df

,EVENT,INDEX,STATUS,ISFINAL,ISCHARGED,MOTHER1,MOTHER2,MOTHER1ID,MOTHER2ID,DAUGHTER1,DAUGHTER2,DAUGHTER1ID,DAUGHTER2ID,DUPLICATED
0,1,418,-23,0,1,317,0,-24,90,420,421,15,22,1
1,1,420,-51,0,1,418,0,15,90,878,881,16,-211,0
2,2,558,-23,0,1,433,0,-24,90,1020,1022,16,-211,0
3,3,481,-23,0,1,349,0,-24,90,483,484,15,22,1
4,3,483,-51,0,1,481,0,15,90,891,892,16,-211,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14143,9997,477,-23,0,1,374,0,-24,90,870,872,16,-12,0
14144,9998,1062,-23,0,1,810,0,-24,90,1846,1848,16,-14,0
14145,9999,645,-23,0,1,495,0,-24,90,1161,1165,16,-211,0
14146,10000,1110,-23,0,1,820,0,-24,90,1112,1113,15,22,1
14147,10000,1112,-51,0,1,1110,0,15,90,1942,1945,16,211,0

In [5]:
dup_event = df['EVENT'].value_counts()>1 # events with more than 1 tau
df_dup = df[df['EVENT'].isin(dup_event[dup_event].index)] # details about such taus
df_dup

,EVENT,INDEX,STATUS,ISFINAL,ISCHARGED,MOTHER1,MOTHER2,MOTHER1ID,MOTHER2ID,DAUGHTER1,DAUGHTER2,DAUGHTER1ID,DAUGHTER2ID,DUPLICATED
0,1,418,-23,0,1,317,0,-24,90,420,421,15,22,1
1,1,420,-51,0,1,418,0,15,90,878,881,16,-211,0
3,3,481,-23,0,1,349,0,-24,90,483,484,15,22,1
4,3,483,-51,0,1,481,0,15,90,891,892,16,-211,0
8,7,150,-23,0,1,103,0,-24,90,152,153,15,22,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14140,9995,1365,-51,0,1,1363,0,15,90,2302,2304,16,-14,0
14141,9996,467,-23,0,1,353,0,-24,90,469,470,15,22,1
14142,9996,469,-51,0,1,467,0,15,90,866,869,16,211,0
14146,10000,1110,-23,0,1,820,0,-24,90,1112,1113,15,22,1
14147,10000,1112,-51,0,1,1110,0,15,90,1942,1945,16,211,0

In [6]:
df_dup['EVENT'].shape, df_dup['EVENT'].unique().shape

((7777,), (3629,))

In [7]:
df['MOTHER1ID'].abs().value_counts() #abs of particle for all imeadite par

MOTHER1ID
24      9895
15      4042
431       78
2         43
1         39
4         12
3         11
511        9
521        7
411        7
531        3
5122       2
Name: count, dtype: int64

In [8]:
df['STATUS'].value_counts()

STATUS
-23    10000
-51     3554
-44      373
-62      105
-91      104
-52       10
-92        2
Name: count, dtype: int64

In [9]:
df['ISFINAL'].sum()

np.int64(0)

Investagae daughters (if daughter1=daughter2>0 => carbon copy of .this):

In [10]:
df_cc = df[df['DAUGHTER1']==df['DAUGHTER2']]
df_cc

,EVENT,INDEX,STATUS,ISFINAL,ISCHARGED,MOTHER1,MOTHER2,MOTHER1ID,MOTHER2ID,DAUGHTER1,DAUGHTER2,DAUGHTER1ID,DAUGHTER2ID,DUPLICATED
33,25,5,-23,0,1,3,4,1,-2,9,9,15,15,1
34,25,9,-44,0,1,5,5,15,15,22,22,15,15,1
35,25,22,-44,0,1,9,9,15,15,154,154,15,15,1
37,25,295,-51,0,1,154,0,15,90,454,454,15,15,1
145,107,5,-23,0,1,3,4,-2,1,16,16,15,15,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14091,9960,5,-23,0,1,3,4,1,-2,13,13,15,15,1
14092,9960,13,-44,0,1,5,5,15,15,111,111,15,15,1
14093,9960,111,-44,0,1,13,13,15,15,120,120,15,15,1
14094,9960,120,-44,0,1,111,111,15,15,259,259,15,15,1
14095,9960,259,-44,0,1,120,120,15,15,621,621,15,15,1

In [11]:
df['EVENT'].value_counts()

EVENT
7006    10
2605     9
6794     9
9010     9
774      9
        ..
4091     1
4090     1
4089     1
4088     1
4104     1
Name: count, Length: 10000, dtype: int64

In [26]:
df[df['EVENT']==7006]

,EVENT,INDEX,STATUS,ISFINAL,ISCHARGED,MOTHER1,MOTHER2,MOTHER1ID,MOTHER2ID,DAUGHTER1,DAUGHTER2,DAUGHTER1ID,DAUGHTER2ID,DUPLICATED
9860,7006,5,-23,0,1,3,4,-4,3,9,9,15,15,1
9861,7006,9,-44,0,1,5,5,15,15,14,14,15,15,1
9862,7006,14,-44,0,1,9,9,15,15,20,20,15,15,1
9863,7006,20,-44,0,1,14,14,15,15,35,35,15,15,1
9864,7006,35,-44,0,1,20,20,15,15,43,43,15,15,1
9865,7006,43,-44,0,1,35,35,15,15,65,65,15,15,1
9866,7006,65,-44,0,1,43,43,15,15,143,143,15,15,1
9867,7006,143,-44,0,1,65,65,15,15,413,413,15,15,1
9868,7006,413,-44,0,1,143,143,15,15,465,465,15,15,1
9869,7006,465,-62,0,1,413,413,15,15,1030,1032,16,-211,0

In [24]:
df[df['DUPLICATED']==0].shape

(10106, 14)

In [25]:
df.shape

(14148, 14)